/* 
 * Ladybug Visualization Schema
 *
 * Documentation for Ladybug visualization schema
 *
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

extern alias LBTNewtonsoft; using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using LBTNewtonsoft::Newtonsoft.Json;
using LBTNewtonsoft::Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace LadybugDisplaySchema
{
    /// <summary>
    /// An object representing context geometry to display.
    /// </summary>
    [Serializable]
    [DataContract(Name = "ContextGeometry")]
    public partial class ContextGeometry : VisualizationBase, IEquatable<ContextGeometry>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContextGeometry" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ContextGeometry() 
        { 
            // Set non-required readonly properties with defaultValue
            this.Type = "ContextGeometry";
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ContextGeometry" /> class.
        /// </summary>
        /// <param name="geometry">A list of ladybug-geometry or ladybug-display objects that gives context to analysis geometry or other aspects of the visualization. Typically, these will display in wireframe around the geometry, though the properties of display geometry can be used to customize the visualization. (required).</param>
        /// <param name="hidden">A boolean to note whether the geometry is hidden by default and must be un-hidden to be visible in the 3D scene. (default to false).</param>
        /// <param name="identifier">Text string for a unique object ID. Must be less than 100 characters and not contain spaces or special characters. (required).</param>
        /// <param name="displayName">Display name of the object with no character restrictions. This is typically used to set the layer of the object in the interface that renders the VisualizationSet. A :: in the display_name can be used to denote sub-layers following a convention of ParentLayer::SubLayer. If not set, the display_name will be equal to the object identifier..</param>
        /// <param name="userData">Optional dictionary of user data associated with the object.All keys and values of this dictionary should be of a standard data type to ensure correct serialization of the object (eg. str, float, int, list)..</param>
        public ContextGeometry
        (
            string identifier, List<AnyOf<IDisplay>> geometry, // Required parameters
            string displayName= default, Object userData= default, bool hidden = false// Optional parameters
        ) : base(identifier: identifier, displayName: displayName, userData: userData )// BaseClass
        {
            // to ensure "geometry" is required (not null)
            this.Geometry = geometry ?? throw new ArgumentNullException("geometry is a required property for ContextGeometry and cannot be null");
            this.Hidden = hidden;

            // Set non-required readonly properties with defaultValue
            this.Type = "ContextGeometry";

            // check if object is valid, only check for inherited class
            if (this.GetType() == typeof(ContextGeometry))
                this.IsValid(throwException: true);
        }

        //============================================== is ReadOnly 
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type")]
        public override string Type { get; protected set; }  = "ContextGeometry";

        /// <summary>
        /// A list of ladybug-geometry or ladybug-display objects that gives context to analysis geometry or other aspects of the visualization. Typically, these will display in wireframe around the geometry, though the properties of display geometry can be used to customize the visualization.
        /// </summary>
        /// <value>A list of ladybug-geometry or ladybug-display objects that gives context to analysis geometry or other aspects of the visualization. Typically, these will display in wireframe around the geometry, though the properties of display geometry can be used to customize the visualization.</value>
        [DataMember(Name = "geometry", IsRequired = true)]
        public List<AnyOf<IDisplay>> Geometry { get; set; } 
        /// <summary>
        /// A boolean to note whether the geometry is hidden by default and must be un-hidden to be visible in the 3D scene.
        /// </summary>
        /// <value>A boolean to note whether the geometry is hidden by default and must be un-hidden to be visible in the 3D scene.</value>
        [DataMember(Name = "hidden")]
        public bool Hidden { get; set; }  = false;

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "ContextGeometry";
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString(bool detailed)
        {
            if (!detailed)
                return this.ToString();
            
            var sb = new StringBuilder();
            sb.Append("ContextGeometry:\n");
            sb.Append("  Type: ").Append(this.Type).Append("\n");
            sb.Append("  Identifier: ").Append(this.Identifier).Append("\n");
            sb.Append("  DisplayName: ").Append(this.DisplayName).Append("\n");
            sb.Append("  UserData: ").Append(this.UserData).Append("\n");
            sb.Append("  Geometry: ").Append(this.Geometry).Append("\n");
            sb.Append("  Hidden: ").Append(this.Hidden).Append("\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the object from JSON string
        /// </summary>
        /// <returns>ContextGeometry object</returns>
        public static ContextGeometry FromJson(string json)
        {
            var obj = JsonConvert.DeserializeObject<ContextGeometry>(json, JsonSetting.AnyOfConvertSetting);
            if (obj == null)
                return null;
            return obj.Type.ToLower() == obj.GetType().Name.ToLower() && obj.IsValid(throwException: true) ? obj : null;
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>ContextGeometry object</returns>
        public virtual ContextGeometry DuplicateContextGeometry()
        {
            return FromJson(this.ToJson());
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>OpenAPIGenBaseModel</returns>
        public override OpenAPIGenBaseModel Duplicate()
        {
            return DuplicateContextGeometry();
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>OpenAPIGenBaseModel</returns>
        public override VisualizationBase DuplicateVisualizationBase()
        {
            return DuplicateContextGeometry();
        }
     
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            input = input is AnyOf anyOf ? anyOf.Obj : input;
            return this.Equals(input as ContextGeometry);
        }

        /// <summary>
        /// Returns true if ContextGeometry instances are equal
        /// </summary>
        /// <param name="input">Instance of ContextGeometry to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ContextGeometry input)
        {
            if (input == null)
                return false;
            return base.Equals(input) && 
                (
                    this.Geometry == input.Geometry ||
                    Extension.AllEquals(this.Geometry, input.Geometry)
                ) && 
                    Extension.Equals(this.Type, input.Type) && 
                    Extension.Equals(this.Hidden, input.Hidden);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Geometry != null)
                    hashCode = hashCode * 59 + this.Geometry.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Hidden != null)
                    hashCode = hashCode * 59 + this.Hidden.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in base.BaseValidate(validationContext)) yield return x;

            
            // Type (string) pattern
            Regex regexType = new Regex(@"^ContextGeometry$", RegexOptions.CultureInvariant);
            if (this.Type != null && false == regexType.Match(this.Type).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Type, must match a pattern of " + regexType, new [] { "Type" });
            }

            yield break;
        }
    }
}
