/* 
 * Ladybug Visualization Schema
 *
 * Documentation for Ladybug visualization schema
 *
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

extern alias LBTNewtonsoft; using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using LBTNewtonsoft::Newtonsoft.Json;
using LBTNewtonsoft::Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace LadybugDisplaySchema
{
    /// <summary>
    /// A text object in 3D space with display properties.
    /// </summary>
    [Serializable]
    [DataContract(Name = "DisplayText3D")]
    public partial class DisplayText3D : DisplayBaseModel, IEquatable<DisplayText3D>, IValidatableObject
    {
        /// <summary>
        /// String to specify the horizontal alignment of the text.
        /// </summary>
        /// <value>String to specify the horizontal alignment of the text.</value>
        [DataMember(Name="horizontal_alignment")]
        public HorizontalAlignments HorizontalAlignment { get; set; } = HorizontalAlignments.Left;
        /// <summary>
        /// String to specify the vertical alignment of the text.
        /// </summary>
        /// <value>String to specify the vertical alignment of the text.</value>
        [DataMember(Name="vertical_alignment")]
        public VerticalAlignments VerticalAlignment { get; set; } = VerticalAlignments.Bottom;
        /// <summary>
        /// Initializes a new instance of the <see cref="DisplayText3D" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DisplayText3D() 
        { 
            // Set non-required readonly properties with defaultValue
            this.Type = "DisplayText3D";
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="DisplayText3D" /> class.
        /// </summary>
        /// <param name="color">Color for the geometry. (required).</param>
        /// <param name="text">A text string to be displayed in the 3D scene. (required).</param>
        /// <param name="plane">A ladybug-geometry Plane object to locate and orient the text in the 3D scene. (required).</param>
        /// <param name="height">A number for the height of the text in the 3D scene. (required).</param>
        /// <param name="font">A text string for the font in which to draw the text. Note that this field may not be interpreted the same on all machines and in all interfaces, particularly when a machine lacks a given font. (default to &quot;Arial&quot;).</param>
        /// <param name="horizontalAlignment">String to specify the horizontal alignment of the text..</param>
        /// <param name="verticalAlignment">String to specify the vertical alignment of the text..</param>
        /// <param name="userData">Optional dictionary of user data associated with the object.All keys and values of this dictionary should be of a standard data type to ensure correct serialization of the object (eg. str, float, int, list)..</param>
        public DisplayText3D
        (
           Color color, string text, Plane plane, double height, // Required parameters
            Object userData= default, string font = "Arial", HorizontalAlignments horizontalAlignment= HorizontalAlignments.Left, VerticalAlignments verticalAlignment= VerticalAlignments.Bottom// Optional parameters
        ) : base(userData: userData )// BaseClass
        {
            // to ensure "color" is required (not null)
            this.Color = color ?? throw new ArgumentNullException("color is a required property for DisplayText3D and cannot be null");
            // to ensure "text" is required (not null)
            this.Text = text ?? throw new ArgumentNullException("text is a required property for DisplayText3D and cannot be null");
            // to ensure "plane" is required (not null)
            this.Plane = plane ?? throw new ArgumentNullException("plane is a required property for DisplayText3D and cannot be null");
            this.Height = height;
            // use default value if no "font" provided
            this.Font = font ?? "Arial";
            this.HorizontalAlignment = horizontalAlignment;
            this.VerticalAlignment = verticalAlignment;

            // Set non-required readonly properties with defaultValue
            this.Type = "DisplayText3D";

            // check if object is valid, only check for inherited class
            if (this.GetType() == typeof(DisplayText3D))
                this.IsValid(throwException: true);
        }

        //============================================== is ReadOnly 
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type")]
        public override string Type { get; protected set; }  = "DisplayText3D";

        /// <summary>
        /// Color for the geometry.
        /// </summary>
        /// <value>Color for the geometry.</value>
        [DataMember(Name = "color", IsRequired = true)]
        public Color Color { get; set; } 
        /// <summary>
        /// A text string to be displayed in the 3D scene.
        /// </summary>
        /// <value>A text string to be displayed in the 3D scene.</value>
        [DataMember(Name = "text", IsRequired = true)]
        public string Text { get; set; } 
        /// <summary>
        /// A ladybug-geometry Plane object to locate and orient the text in the 3D scene.
        /// </summary>
        /// <value>A ladybug-geometry Plane object to locate and orient the text in the 3D scene.</value>
        [DataMember(Name = "plane", IsRequired = true)]
        public Plane Plane { get; set; } 
        /// <summary>
        /// A number for the height of the text in the 3D scene.
        /// </summary>
        /// <value>A number for the height of the text in the 3D scene.</value>
        [DataMember(Name = "height", IsRequired = true)]
        public double Height { get; set; } 
        /// <summary>
        /// A text string for the font in which to draw the text. Note that this field may not be interpreted the same on all machines and in all interfaces, particularly when a machine lacks a given font.
        /// </summary>
        /// <value>A text string for the font in which to draw the text. Note that this field may not be interpreted the same on all machines and in all interfaces, particularly when a machine lacks a given font.</value>
        [DataMember(Name = "font")]
        public string Font { get; set; }  = "Arial";

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "DisplayText3D";
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString(bool detailed)
        {
            if (!detailed)
                return this.ToString();
            
            var sb = new StringBuilder();
            sb.Append("DisplayText3D:\n");
            sb.Append("  Type: ").Append(this.Type).Append("\n");
            sb.Append("  UserData: ").Append(this.UserData).Append("\n");
            sb.Append("  Color: ").Append(this.Color).Append("\n");
            sb.Append("  Text: ").Append(this.Text).Append("\n");
            sb.Append("  Plane: ").Append(this.Plane).Append("\n");
            sb.Append("  Height: ").Append(this.Height).Append("\n");
            sb.Append("  Font: ").Append(this.Font).Append("\n");
            sb.Append("  HorizontalAlignment: ").Append(this.HorizontalAlignment).Append("\n");
            sb.Append("  VerticalAlignment: ").Append(this.VerticalAlignment).Append("\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the object from JSON string
        /// </summary>
        /// <returns>DisplayText3D object</returns>
        public static DisplayText3D FromJson(string json)
        {
            var obj = JsonConvert.DeserializeObject<DisplayText3D>(json, JsonSetting.AnyOfConvertSetting);
            if (obj == null)
                return null;
            return obj.Type.ToLower() == obj.GetType().Name.ToLower() && obj.IsValid(throwException: true) ? obj : null;
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>DisplayText3D object</returns>
        public virtual DisplayText3D DuplicateDisplayText3D()
        {
            return FromJson(this.ToJson());
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>OpenAPIGenBaseModel</returns>
        public override OpenAPIGenBaseModel Duplicate()
        {
            return DuplicateDisplayText3D();
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>OpenAPIGenBaseModel</returns>
        public override DisplayBaseModel DuplicateDisplayBaseModel()
        {
            return DuplicateDisplayText3D();
        }
     
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            input = input is AnyOf anyOf ? anyOf.Obj : input;
            return this.Equals(input as DisplayText3D);
        }

        /// <summary>
        /// Returns true if DisplayText3D instances are equal
        /// </summary>
        /// <param name="input">Instance of DisplayText3D to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DisplayText3D input)
        {
            if (input == null)
                return false;
            return base.Equals(input) && 
                    Extension.Equals(this.Color, input.Color) && 
                    Extension.Equals(this.Text, input.Text) && 
                    Extension.Equals(this.Plane, input.Plane) && 
                    Extension.Equals(this.Height, input.Height) && 
                    Extension.Equals(this.Type, input.Type) && 
                    Extension.Equals(this.Font, input.Font) && 
                    Extension.Equals(this.HorizontalAlignment, input.HorizontalAlignment) && 
                    Extension.Equals(this.VerticalAlignment, input.VerticalAlignment);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Color != null)
                    hashCode = hashCode * 59 + this.Color.GetHashCode();
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                if (this.Plane != null)
                    hashCode = hashCode * 59 + this.Plane.GetHashCode();
                if (this.Height != null)
                    hashCode = hashCode * 59 + this.Height.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Font != null)
                    hashCode = hashCode * 59 + this.Font.GetHashCode();
                if (this.HorizontalAlignment != null)
                    hashCode = hashCode * 59 + this.HorizontalAlignment.GetHashCode();
                if (this.VerticalAlignment != null)
                    hashCode = hashCode * 59 + this.VerticalAlignment.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in base.BaseValidate(validationContext)) yield return x;

            
            // Type (string) pattern
            Regex regexType = new Regex(@"^DisplayText3D$", RegexOptions.CultureInvariant);
            if (this.Type != null && false == regexType.Match(this.Type).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Type, must match a pattern of " + regexType, new [] { "Type" });
            }

            yield break;
        }
    }
}
