/* 
 * Ladybug Display Schema
 *
 * Documentation for Ladybug display schema
 *
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace LadybugDisplaySchema
{
    /// <summary>
    /// Optional edge information for Polyface.
    /// </summary>
    [Serializable]
    [DataContract(Name = "PolyfaceEdgeInfo")]
    public partial class PolyfaceEdgeInfo : OpenAPIGenBaseModel, IEquatable<PolyfaceEdgeInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PolyfaceEdgeInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PolyfaceEdgeInfo() 
        { 
            // Set non-required readonly properties with defaultValue
            this.Type = "PolyfaceEdgeInfo";
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="PolyfaceEdgeInfo" /> class.
        /// </summary>
        /// <param name="edgeIndices">An array objects that each contain two integers. These integers correspond to indices within the vertices list and each tuple represents a line segment for an edge of the polyface. (required).</param>
        /// <param name="edgeTypes">An array of integers for each edge that parallels the edge_indices list. An integer of 0 denotes a naked edge, an integer of 1 denotes an internal edge. Anything higher is a non-manifold edge. (required).</param>
        public PolyfaceEdgeInfo
        (
           List<List<int>> edgeIndices, List<int> edgeTypes// Required parameters
            // Optional parameters
        ) : base()// BaseClass
        {
            // to ensure "edgeIndices" is required (not null)
            this.EdgeIndices = edgeIndices ?? throw new ArgumentNullException("edgeIndices is a required property for PolyfaceEdgeInfo and cannot be null");
            // to ensure "edgeTypes" is required (not null)
            this.EdgeTypes = edgeTypes ?? throw new ArgumentNullException("edgeTypes is a required property for PolyfaceEdgeInfo and cannot be null");

            // Set non-required readonly properties with defaultValue
            this.Type = "PolyfaceEdgeInfo";

            // check if object is valid, only check for inherited class
            if (this.GetType() == typeof(PolyfaceEdgeInfo))
                this.IsValid(throwException: true);
        }

        //============================================== is ReadOnly 
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type")]
        public override string Type { get; protected set; }  = "PolyfaceEdgeInfo";

        /// <summary>
        /// An array objects that each contain two integers. These integers correspond to indices within the vertices list and each tuple represents a line segment for an edge of the polyface.
        /// </summary>
        /// <value>An array objects that each contain two integers. These integers correspond to indices within the vertices list and each tuple represents a line segment for an edge of the polyface.</value>
        [DataMember(Name = "edge_indices", IsRequired = true)]
        public List<List<int>> EdgeIndices { get; set; } 
        /// <summary>
        /// An array of integers for each edge that parallels the edge_indices list. An integer of 0 denotes a naked edge, an integer of 1 denotes an internal edge. Anything higher is a non-manifold edge.
        /// </summary>
        /// <value>An array of integers for each edge that parallels the edge_indices list. An integer of 0 denotes a naked edge, an integer of 1 denotes an internal edge. Anything higher is a non-manifold edge.</value>
        [DataMember(Name = "edge_types", IsRequired = true)]
        public List<int> EdgeTypes { get; set; } 

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "PolyfaceEdgeInfo";
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString(bool detailed)
        {
            if (!detailed)
                return this.ToString();
            
            var sb = new StringBuilder();
            sb.Append("PolyfaceEdgeInfo:\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  EdgeIndices: ").Append(EdgeIndices).Append("\n");
            sb.Append("  EdgeTypes: ").Append(EdgeTypes).Append("\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the object from JSON string
        /// </summary>
        /// <returns>PolyfaceEdgeInfo object</returns>
        public static PolyfaceEdgeInfo FromJson(string json)
        {
            var obj = JsonConvert.DeserializeObject<PolyfaceEdgeInfo>(json, JsonSetting.AnyOfConvertSetting);
            if (obj == null)
                return null;
            return obj.Type.ToLower() == obj.GetType().Name.ToLower() && obj.IsValid(throwException: true) ? obj : null;
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>PolyfaceEdgeInfo object</returns>
        public virtual PolyfaceEdgeInfo DuplicatePolyfaceEdgeInfo()
        {
            return FromJson(this.ToJson());
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>OpenAPIGenBaseModel</returns>
        public override OpenAPIGenBaseModel Duplicate()
        {
            return DuplicatePolyfaceEdgeInfo();
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>OpenAPIGenBaseModel</returns>
        public override OpenAPIGenBaseModel DuplicateOpenAPIGenBaseModel()
        {
            return DuplicatePolyfaceEdgeInfo();
        }
     
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            input = input is AnyOf anyOf ? anyOf.Obj : input;
            return this.Equals(input as PolyfaceEdgeInfo);
        }

        /// <summary>
        /// Returns true if PolyfaceEdgeInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of PolyfaceEdgeInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PolyfaceEdgeInfo input)
        {
            if (input == null)
                return false;
            return base.Equals(input) && 
                (
                    this.EdgeIndices == input.EdgeIndices ||
                    Extension.AllEquals(this.EdgeIndices, input.EdgeIndices)
                ) && 
                (
                    this.EdgeTypes == input.EdgeTypes ||
                    Extension.AllEquals(this.EdgeTypes, input.EdgeTypes)
                ) && 
                    Extension.Equals(this.Type, input.Type);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.EdgeIndices != null)
                    hashCode = hashCode * 59 + this.EdgeIndices.GetHashCode();
                if (this.EdgeTypes != null)
                    hashCode = hashCode * 59 + this.EdgeTypes.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in base.BaseValidate(validationContext)) yield return x;

            

            

            
            // Type (string) pattern
            Regex regexType = new Regex(@"^PolyfaceEdgeInfo$", RegexOptions.CultureInvariant);
            if (this.Type != null && false == regexType.Match(this.Type).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Type, must match a pattern of " + regexType, new [] { "Type" });
            }

            yield break;
        }
    }
}
