/* 
 * Ladybug Display Schema
 *
 * Documentation for Ladybug display schema
 *
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace LadybugDisplaySchema
{
    /// <summary>
    /// A polygon in 2D space (without holes).
    /// </summary>
    [Serializable]
    [DataContract(Name = "Polygon2D")]
    public partial class Polygon2D : OpenAPIGenBaseModel, IEquatable<Polygon2D>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Polygon2D" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Polygon2D() 
        { 
            // Set non-required readonly properties with defaultValue
            this.Type = "Polygon2D";
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Polygon2D" /> class.
        /// </summary>
        /// <param name="vertices">A list of points representing the vertices of the polygon. The list should include at least 3 points and each point should be a list of 2 (x, y) values. (required).</param>
        public Polygon2D
        (
           List<List<double>> vertices// Required parameters
            // Optional parameters
        ) : base()// BaseClass
        {
            // to ensure "vertices" is required (not null)
            this.Vertices = vertices ?? throw new ArgumentNullException("vertices is a required property for Polygon2D and cannot be null");

            // Set non-required readonly properties with defaultValue
            this.Type = "Polygon2D";

            // check if object is valid, only check for inherited class
            if (this.GetType() == typeof(Polygon2D))
                this.IsValid(throwException: true);
        }

        //============================================== is ReadOnly 
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type")]
        public override string Type { get; protected set; }  = "Polygon2D";

        /// <summary>
        /// A list of points representing the vertices of the polygon. The list should include at least 3 points and each point should be a list of 2 (x, y) values.
        /// </summary>
        /// <value>A list of points representing the vertices of the polygon. The list should include at least 3 points and each point should be a list of 2 (x, y) values.</value>
        [DataMember(Name = "vertices", IsRequired = true)]
        public List<List<double>> Vertices { get; set; } 

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "Polygon2D";
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString(bool detailed)
        {
            if (!detailed)
                return this.ToString();
            
            var sb = new StringBuilder();
            sb.Append("Polygon2D:\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Vertices: ").Append(Vertices).Append("\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the object from JSON string
        /// </summary>
        /// <returns>Polygon2D object</returns>
        public static Polygon2D FromJson(string json)
        {
            var obj = JsonConvert.DeserializeObject<Polygon2D>(json, JsonSetting.AnyOfConvertSetting);
            if (obj == null)
                return null;
            return obj.Type.ToLower() == obj.GetType().Name.ToLower() && obj.IsValid(throwException: true) ? obj : null;
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>Polygon2D object</returns>
        public virtual Polygon2D DuplicatePolygon2D()
        {
            return FromJson(this.ToJson());
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>OpenAPIGenBaseModel</returns>
        public override OpenAPIGenBaseModel Duplicate()
        {
            return DuplicatePolygon2D();
        }

        /// <summary>
        /// Creates a new instance with the same properties.
        /// </summary>
        /// <returns>OpenAPIGenBaseModel</returns>
        public override OpenAPIGenBaseModel DuplicateOpenAPIGenBaseModel()
        {
            return DuplicatePolygon2D();
        }
     
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            input = input is AnyOf anyOf ? anyOf.Obj : input;
            return this.Equals(input as Polygon2D);
        }

        /// <summary>
        /// Returns true if Polygon2D instances are equal
        /// </summary>
        /// <param name="input">Instance of Polygon2D to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Polygon2D input)
        {
            if (input == null)
                return false;
            return base.Equals(input) && 
                (
                    this.Vertices == input.Vertices ||
                    Extension.AllEquals(this.Vertices, input.Vertices)
                ) && 
                    Extension.Equals(this.Type, input.Type);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Vertices != null)
                    hashCode = hashCode * 59 + this.Vertices.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in base.BaseValidate(validationContext)) yield return x;

            

            
            // Type (string) pattern
            Regex regexType = new Regex(@"^Polygon2D$", RegexOptions.CultureInvariant);
            if (this.Type != null && false == regexType.Match(this.Type).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Type, must match a pattern of " + regexType, new [] { "Type" });
            }

            yield break;
        }
    }
}
