//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace LadybugDisplaySchema
{
	public partial interface IBase {}
}

//Classes implemented this interface:
namespace LadybugDisplaySchema
{
	public partial class Color: LadybugDisplaySchema.IBase {}
	public partial class Default: LadybugDisplaySchema.IBase {}
}
