//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace LadybugDisplaySchema
{
	public partial interface IDisplay3D {}
}

//Classes implemented this interface:
namespace LadybugDisplaySchema
{
	public partial class DisplayArc3D: LadybugDisplaySchema.IDisplay3D {}
	public partial class DisplayCone: LadybugDisplaySchema.IDisplay3D {}
	public partial class DisplayCylinder: LadybugDisplaySchema.IDisplay3D {}
	public partial class DisplayFace3D: LadybugDisplaySchema.IDisplay3D {}
	public partial class DisplayLineSegment3D: LadybugDisplaySchema.IDisplay3D {}
	public partial class DisplayMesh3D: LadybugDisplaySchema.IDisplay3D {}
	public partial class DisplayPlane: LadybugDisplaySchema.IDisplay3D {}
	public partial class DisplayPoint3D: LadybugDisplaySchema.IDisplay3D {}
	public partial class DisplayPolyface3D: LadybugDisplaySchema.IDisplay3D {}
	public partial class DisplayPolyline3D: LadybugDisplaySchema.IDisplay3D {}
	public partial class DisplayRay3D: LadybugDisplaySchema.IDisplay3D {}
	public partial class DisplaySphere: LadybugDisplaySchema.IDisplay3D {}
	public partial class DisplayText3D: LadybugDisplaySchema.IDisplay3D {}
	public partial class DisplayVector3D: LadybugDisplaySchema.IDisplay3D {}
}
