//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace LadybugDisplaySchema
{
	public partial interface IDisplay2D {}
}

//Classes implemented this interface:
namespace LadybugDisplaySchema
{
	public partial class DisplayArc2D: LadybugDisplaySchema.IDisplay2D {}
	public partial class DisplayLineSegment2D: LadybugDisplaySchema.IDisplay2D {}
	public partial class DisplayMesh2D: LadybugDisplaySchema.IDisplay2D {}
	public partial class DisplayPoint2D: LadybugDisplaySchema.IDisplay2D {}
	public partial class DisplayPolygon2D: LadybugDisplaySchema.IDisplay2D {}
	public partial class DisplayPolyline2D: LadybugDisplaySchema.IDisplay2D {}
	public partial class DisplayRay2D: LadybugDisplaySchema.IDisplay2D {}
	public partial class DisplayVector2D: LadybugDisplaySchema.IDisplay2D {}
}
