//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace LadybugDisplaySchema
{
	public partial interface IGeometry2D {}
}

//Classes implemented this interface:
namespace LadybugDisplaySchema
{
	public partial class Arc2D: LadybugDisplaySchema.IGeometry2D {}
	public partial class LineSegment2D: LadybugDisplaySchema.IGeometry2D {}
	public partial class Mesh2D: LadybugDisplaySchema.IGeometry2D {}
	public partial class Point2D: LadybugDisplaySchema.IGeometry2D {}
	public partial class Polygon2D: LadybugDisplaySchema.IGeometry2D {}
	public partial class Polyline2D: LadybugDisplaySchema.IGeometry2D {}
	public partial class Ray2D: LadybugDisplaySchema.IGeometry2D {}
	public partial class Vector2D: LadybugDisplaySchema.IGeometry2D {}
}
