//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace LadybugDisplaySchema
{
	public partial interface IGeometry3D {}
}

//Classes implemented this interface:
namespace LadybugDisplaySchema
{
	public partial class Arc3D: LadybugDisplaySchema.IGeometry3D {}
	public partial class Cone: LadybugDisplaySchema.IGeometry3D {}
	public partial class Cylinder: LadybugDisplaySchema.IGeometry3D {}
	public partial class Face3D: LadybugDisplaySchema.IGeometry3D {}
	public partial class LineSegment3D: LadybugDisplaySchema.IGeometry3D {}
	public partial class Mesh3D: LadybugDisplaySchema.IGeometry3D {}
	public partial class Plane: LadybugDisplaySchema.IGeometry3D {}
	public partial class Point3D: LadybugDisplaySchema.IGeometry3D {}
	public partial class Polyface3D: LadybugDisplaySchema.IGeometry3D {}
	public partial class PolyfaceEdgeInfo: LadybugDisplaySchema.IGeometry3D {}
	public partial class Polyline3D: LadybugDisplaySchema.IGeometry3D {}
	public partial class Ray3D: LadybugDisplaySchema.IGeometry3D {}
	public partial class Sphere: LadybugDisplaySchema.IGeometry3D {}
	public partial class Vector3D: LadybugDisplaySchema.IGeometry3D {}
}
