//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace LadybugDisplaySchema
{
	public partial interface IGraphic {}
}

//Classes implemented this interface:
namespace LadybugDisplaySchema
{
	public partial class DataType: LadybugDisplaySchema.IGraphic {}
	public partial class GraphicContainer: LadybugDisplaySchema.IGraphic {}
	public partial class LegendParameters: LadybugDisplaySchema.IGraphic {}
}
