//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace LadybugDisplaySchema
{
	public partial interface IVisualization {}
}

//Classes implemented this interface:
namespace LadybugDisplaySchema
{
	public partial class AnalysisGeometry: LadybugDisplaySchema.IVisualization {}
	public partial class ContextGeometry: LadybugDisplaySchema.IVisualization {}
	public partial class DataType: LadybugDisplaySchema.IVisualization {}
	public partial class GenericDataType: LadybugDisplaySchema.IVisualization {}
	public partial class Legend2DParameters: LadybugDisplaySchema.IVisualization {}
	public partial class Legend3DParameters: LadybugDisplaySchema.IVisualization {}
	public partial class LegendParameters: LadybugDisplaySchema.IVisualization {}
	public partial class VisualizationData: LadybugDisplaySchema.IVisualization {}
	public partial class VisualizationMetaData: LadybugDisplaySchema.IVisualization {}
	public partial class VisualizationSet: LadybugDisplaySchema.IVisualization {}
}
